Using the BeautifulSoup

In [1]:
from bs4 import BeautifulSoup

In [4]:
with open("htmls/page1.html") as f:
    content = f.read()
soup = BeautifulSoup(content,"html.parser")
h3s = soup.find_all("h3")
articles = soup.select("article.product_pod")
items = []
for article in articles:
    title = article.find("h3").find("a")["title"]
    price = article.select_one("p.price_color").text.split("£")[1]
    rating_element = article.select_one("p.star-rating")
    rate = rating_element["class"][1]
    items.append([title,price,rate])

In [6]:
import pandas as pd
df = pd.DataFrame(items,columns=["Book Name","Prices","Ratings"])
df

                                            Book Name Prices Ratings
0                                A Light in the Attic  51.77   Three
1                                  Tipping the Velvet  53.74     One
2                                          Soumission  50.10     One
3                                       Sharp Objects  47.82    Four
4               Sapiens: A Brief History of Humankind  54.23    Five
5                                     The Requiem Red  22.65     One
6   The Dirty Little Secrets of Getting Your Dream...  33.34    Four
7   The Coming Woman: A Novel Based on the Life of...  17.93   Three
8   The Boys in the Boat: Nine Americans and Their...  22.60    Four
9                                     The Black Maria  52.15     One
10     Starving Hearts (Triangular Trade Trilogy, #1)  13.99     Two
11                              Shakespeare's Sonnets  20.66    Four
12                                        Set Me Free  17.46    Five
13  Scott Pilgrim's Precious Little Life (Scott Pi...  52.29    Five
14                          Rip it Up and Start Again  35.02    Five
15  Our Band Could Be Your Life: Scenes from the A...  57.25   Three
16                                               Olio  23.88     One
17  Mesaerion: The Best Science Fiction Stories 18...  37.59     One
18                       Libertarianism for Beginners  51.33     Two
19                            It's Only the Himalayas  45.17     Two

In [18]:
three = []
four = []
five = []
for item in items:
    if item[2] == "Three":
        three.append([item[0],item[2]])
    elif item[2] == "Four":
        four.append([item[0],item[2]])
    elif item[2] == "Five":
        five.append([item[0],item[2]])
    else:
        pass
print("Five star rating : ",five)
print("Four star rating : ",four)
print("Three star rating : ",three)

Five star rating :  [['Sapiens: A Brief History of Humankind', 'Five'], ['Set Me Free', 'Five'], ["Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)", 'Five'], ['Rip it Up and Start Again', 'Five']]
Four star rating :  [['Sharp Objects', 'Four'], ['The Dirty Little Secrets of Getting Your Dream Job', 'Four'], ['The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics', 'Four'], ["Shakespeare's Sonnets", 'Four']]
Three star rating :  [['A Light in the Attic', 'Three'], ['The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull', 'Three'], ['Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991', 'Three']]

In [19]:
df_three = pd.DataFrame(three,columns=["Book Name","Ratings"])
df_three

                                           Book Name Ratings
0                               A Light in the Attic   Three
1  The Coming Woman: A Novel Based on the Life of...   Three
2  Our Band Could Be Your Life: Scenes from the A...   Three

In [20]:
df_four = pd.DataFrame(four,columns=["Book Name","Ratings"])
df_four

                                           Book Name Ratings
0                                      Sharp Objects    Four
1  The Dirty Little Secrets of Getting Your Dream...    Four
2  The Boys in the Boat: Nine Americans and Their...    Four
3                              Shakespeare's Sonnets    Four

In [21]:
df_five = pd.DataFrame(five,columns=["Book Name","Ratings"])
df_five

                                           Book Name Ratings
0              Sapiens: A Brief History of Humankind    Five
1                                        Set Me Free    Five
2  Scott Pilgrim's Precious Little Life (Scott Pi...    Five
3                          Rip it Up and Start Again    Five